-- DDL generated by Postico 1.5.8
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE issues (
    id bigint PRIMARY KEY,
    issued_book bigint,
    start_time timestamp without time zone,
    finish_time timestamp without time zone,
    issued_by bigint,
    return_time timestamp without time zone
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX issues_pkey ON issues(id int8_ops);
