version: '2'
services:
    postgres:
        image: "postgres"

        container_name: "my_postgres"

        environment:
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=
        - POSTGRES_DB=gci_book
    
        ports:
        - "54320:5432"
 
        volumes:
        - ./postgres-data:/var/lib/postgresql/data
